export const navBarList = [
  { title: "Home", pathName: "/" },
  { title: "About Us", pathName: "/about" },
  { title: "Tutors", pathName: "/tutors" },
  { title: "Students", pathName: "/students" },
  { title: "Contact Us", pathName: "/contact" },
];

export const courseList = [
  { icon: "devicon:angular", text: "Angular" },
  { icon: "logos:react", text: "React" },
  { icon: "vscode-icons:file-type-css", text: "Css" },
  { icon: "devicon:tailwindcss", text: "Tailwind Css" },
  { icon: "logos:nodejs", text: "Node JS" },
  { icon: "devicon:nestjs-wordmark", text: "Nest JS" },
  { icon: "logos:nextjs", text: "Next JS" },
  { icon: "devicon:mongodb-wordmark", text: "MongoDB" },
  { icon: "devicon:postgresql-wordmark", text: "PostgreSql" },
];

export const coursesCardList = [
  {
    title: "Web Development Fundamentals",
    instructor: "John Doe",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?programming",
    price: "FREE",
    length: "4 weeks",
    moduleLength: 12,
    starRating: 4.5,
    lessons: 36,
  },
  {
    title: "Graphic Design Basics",
    instructor: "Jane Smith",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?design",
    price: 39.99,
    length: "6 weeks",
    moduleLength: 8,
    starRating: 4.2,
    lessons: 24,
  },
  {
    title: "Business Strategies",
    instructor: "Alex Johnson",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?business",
    price: 59.99,
    length: "5 weeks",
    moduleLength: 10,
    starRating: 4.8,
    lessons: 30,
  },
  {
    title: "Digital Marketing Essentials",
    instructor: "Emily Davis",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?marketing",
    price: "FREE",
    length: "3 weeks",
    moduleLength: 6,
    starRating: 4.0,
    lessons: 18,
  },
  {
    title: "Technology Innovations",
    instructor: "Samuel Wilson",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?technology",
    price: 79.99,
    length: "8 weeks",
    moduleLength: 15,
    starRating: 4.7,
    lessons: 45,
  },
  {
    title: "Photography for Beginners",
    instructor: "Sophie Adams",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?photography",
    price: 54.99,
    length: "7 weeks",
    moduleLength: 11,
    starRating: 4.6,
    lessons: 42,
  },
  {
    title: "Finance Management Strategies",
    instructor: "Michael Brown",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?finance",
    price: 69.99,
    length: "9 weeks",
    moduleLength: 14,
    starRating: 4.9,
    lessons: 50,
  },
  {
    title: "Art Appreciation",
    instructor: "Eva Green",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?art",
    price: 44.99,
    length: "5 weeks",
    moduleLength: 9,
    starRating: 4.4,
    lessons: 28,
  },
  {
    title: "Music Theory Basics",
    instructor: "Christopher Turner",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?music",
    price: 34.99,
    length: "4 weeks",
    moduleLength: 7,
    starRating: 4.3,
    lessons: 21,
  },
  {
    title: "Healthy Living Practices",
    instructor: "Olivia White",
    instructorImg: "https://source.unsplash.com/100x100/?portrait",
    img: "https://source.unsplash.com/800x600/?health",
    price: 59.99,
    length: "6 weeks",
    moduleLength: 10,
    starRating: 4.7,
    lessons: 36,
  },
];
